---
person:
  name: Brett
  email: 
    -bpholman5@gmail.com
  profiles:
   profile:
      location_urls:
        -https://www.indeed.com/jobs?q=&I=santa+fe%2C+nm
        -https://santafe.craigslist.org/search/sof
        -https://santafe.craigslist.org/search/sad
        -https://santafe.craigslist.org/search/web
        -https://santafe.craigslist.org/search/eng
      keywords:
        find:
          -remote
          -equity
          -consultant
          -consulting
          -c++
          -pnuts
          -ftpc
          -mes
          -python
          -perl
          -bash
          -linux
          -nix
        exclude:
          -part time
          -part-time
          -temporary
          -freelance 

