---
person:
  name: your-name
  email: 
    -your-email@gmail.com
  profiles:
   profile:
      location_urls:
        -https://eauclaire.craigslist.org/search/web
        -https://eauclaire.craigslist.org/search/sad
        -https://eauclaire.craigslist.org/search/eng
        -https://madison.craigslist.org/search/sof
        -https://minneapolis.craigslist.org/search/sof
      keywords:
        find:
          -remote
          -equity
          -c++
          -python
          -bash
          -linux
        exclude:
          -part time
          -part-time
          -temporary

